"""Validate the deliverable ZIP in a fresh workspace extraction, no old edits."""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import zipfile

WORK = Path(__file__).resolve().parent
OUTPUTS = WORK.parent / "outputs"
SOURCE = OUTPUTS / "PLM-L1-v0.2"
ARCHIVE = OUTPUTS / "PLM-L1-v0.2.zip"
EXTRACT = WORK / "plm-l1-v02-package-extracted"
VERIFY = WORK / "plm-l1-v02-package-verification"


def snapshot(folder):
    return {p.relative_to(folder).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest() for p in folder.rglob("*") if p.is_file()}


assert not EXTRACT.exists() and not VERIFY.exists()
assert EXTRACT.resolve().is_relative_to(WORK.resolve())
expected = snapshot(SOURCE)
archive_hash = hashlib.sha256(ARCHIVE.read_bytes()).hexdigest()
EXTRACT.mkdir()
with zipfile.ZipFile(ARCHIVE) as archive:
    for member in archive.infolist():
        if not (EXTRACT / member.filename).resolve().is_relative_to(EXTRACT.resolve()):
            raise ValueError("unsafe archive path")
    if archive.testzip() is not None:
        raise ValueError("CRC failure")
    archive.extractall(EXTRACT)
extracted = EXTRACT / SOURCE.name
assert snapshot(extracted) == expected
env = dict(os.environ, OPENBLAS_NUM_THREADS="1", PYTHONIOENCODING="utf-8", PYTHONDONTWRITEBYTECODE="1", PYTHONNOUSERSITE="1")
env.pop("PYTHONPATH", None)
result = subprocess.run([sys.executable, "-B", "verify_release.py", "--out", str(VERIFY)], cwd=extracted,
                        env=env, capture_output=True, text=True, encoding="utf-8", timeout=240)
(WORK / "plm-l1-v02-package-verification.log").write_text(result.stdout + result.stderr, encoding="utf-8")
if result.returncode:
    raise ValueError("extracted verification failed: " + result.stderr)
packet = extracted / "CLI_TEMP_PACKET.json"
assert not packet.exists() and packet.resolve().parent == extracted.resolve()
try:
    commands = [
        ["-m", "plm_l1_v02", "read", "--model", "results/reader", "--text", "太郎が花子を助けた。", "--out", packet.name],
        ["-m", "plm_l1_v02", "generate", "--model", "results/reader", "--packet", packet.name],
        ["-c", "from evaluate import verify_freeze; print(verify_freeze())"],
    ]
    for i, command in enumerate(commands):
        execution = subprocess.run([sys.executable, "-B", *command], cwd=extracted, env=env, capture_output=True, text=True, encoding="utf-8", timeout=60)
        if execution.returncode:
            raise ValueError("root packet/CLI regression: " + execution.stderr)
        if i == 1:
            assert json.loads(execution.stdout)["text"] == "花子を太郎が助けた。"
finally:
    # Exact file was absent before this check and was generated by our CLI.
    if packet.exists():
        packet.unlink()
assert snapshot(extracted) == expected and snapshot(SOURCE) == expected
assert hashlib.sha256(ARCHIVE.read_bytes()).hexdigest() == archive_hash
record = json.loads((VERIFY / "VERIFICATION.json").read_text(encoding="utf-8"))
record.update(archive=str(ARCHIVE), archive_sha256=archive_hash, archive_bytes=ARCHIVE.stat().st_size,
              archive_files=len(expected), extracted_bytes_equal=True, source_and_archive_unchanged=True,
              convenience_generate_cli_passed=True, root_json_source_guard_passed=True)
with (OUTPUTS / "PLM-L1-v0.2-VERIFICATION.json").open("x", encoding="utf-8") as stream:
    stream.write(json.dumps(record, ensure_ascii=False, indent=2) + "\n")
print(json.dumps(record, ensure_ascii=False, indent=2))
